/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.javaseminar.kafa.bookregister.gui;

import cz.muni.fi.javaseminar.kafa.bookregister.gui.actions.SpawnNewAuthorWindow;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.actions.SpawnNewBookWindow;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.model.AuthorsTableModel;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.model.BooksTableModel;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.workers.AuthorBackendWorker;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.workers.BookBackendWorker;
import java.awt.Component;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JTable;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.SwingUtilities;
import javax.swing.SwingWorker;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.PopupMenuEvent;
import javax.swing.event.PopupMenuListener;
import javax.swing.table.DefaultTableCellRenderer;
import org.jdesktop.swingx.table.DatePickerCellEditor;

/**
 *
 * @author Martin
 */
public class MainWindow extends javax.swing.JFrame {

    private final SpawnNewAuthorWindow spawnNewAuthorWindowAction = new SpawnNewAuthorWindow("New author...", this);
    private final SpawnNewBookWindow spawnNewBookWindowAction = new SpawnNewBookWindow("New book...", this);

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        authorsTableModel = new AuthorsTableModel();
        booksTableModel = new BooksTableModel();

        initComponents();

        this.addWindowFocusListener(new WindowAdapter() {
            @Override
            public void windowGainedFocus(WindowEvent e) {
                updateModel();
            }
        });

        booksTable.getColumnModel().getColumn(2).setCellEditor(new DatePickerCellEditor(new SimpleDateFormat("dd. MM. yyyy")));
        booksTable.getColumnModel().getColumn(2).setCellRenderer(new DateCellRenderer());
        booksTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        authorsTable.getColumnModel().getColumn(2).setCellEditor(new DatePickerCellEditor(new SimpleDateFormat("dd. MM. yyyy")));
        authorsTable.getColumnModel().getColumn(2).setCellRenderer(new DateCellRenderer());
        authorsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        ListSelectionModel selectionModel = authorsTable.getSelectionModel();
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                DefaultListSelectionModel source = (DefaultListSelectionModel) e.getSource();
                if (source.getMinSelectionIndex() >= 0) {
                    authorsTableModel.setCurrentSlectedIndex(source.getMinSelectionIndex());
                }

                booksTableModel.setAuthorIndex(source.getMinSelectionIndex());
            }
        });

        initPopupMenus();

        newAuthorMenuItem.setAction(spawnNewAuthorWindowAction);
        newBookMenuItem.setAction(spawnNewBookWindowAction);
        newAuthorMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_A, KeyEvent.CTRL_DOWN_MASK));
        newBookMenuItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_B, KeyEvent.CTRL_DOWN_MASK));
    }

    public void updateModel() {
        authorsTableModel.updateData();

        if (authorsTableModel.getRowCount() > 0) {
            authorsTable.setRowSelectionInterval(authorsTableModel.getCurrentSlectedIndex(), authorsTableModel.getCurrentSlectedIndex());
            spawnNewBookWindowAction.setEnabled(true);
        } else {
            spawnNewBookWindowAction.setEnabled(false);
        }

        booksTableModel.updateData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authorsPanel = new javax.swing.JPanel();
        authorsLabel = new javax.swing.JLabel();
        authorsScrollPane = new javax.swing.JScrollPane();
        authorsTable = new javax.swing.JTable();
        booksPanel = new javax.swing.JPanel();
        booksScrollPane = new javax.swing.JScrollPane();
        booksTable = new javax.swing.JTable();
        booksLabel = new javax.swing.JLabel();
        mainMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newAuthorMenuItem = new javax.swing.JMenuItem();
        newBookMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Book Register 1.0");
        setMinimumSize(new java.awt.Dimension(1024, 480));
        setPreferredSize(new java.awt.Dimension(1024, 640));
        getContentPane().setLayout(new java.awt.GridLayout(2, 1));

        authorsPanel.setLayout(new java.awt.BorderLayout());

        authorsLabel.setText("Authors");
        authorsPanel.add(authorsLabel, java.awt.BorderLayout.PAGE_START);

        authorsTable.setModel(authorsTableModel);
        authorsTable.setMinimumSize(new java.awt.Dimension(480, 640));
        authorsScrollPane.setViewportView(authorsTable);

        authorsPanel.add(authorsScrollPane, java.awt.BorderLayout.CENTER);

        getContentPane().add(authorsPanel);

        booksPanel.setLayout(new java.awt.BorderLayout());

        booksTable.setModel(booksTableModel);
        booksScrollPane.setViewportView(booksTable);

        booksPanel.add(booksScrollPane, java.awt.BorderLayout.CENTER);

        booksLabel.setText("Books");
        booksPanel.add(booksLabel, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(booksPanel);

        fileMenu.setText("File");
        fileMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileMenuActionPerformed(evt);
            }
        });

        newAuthorMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        newAuthorMenuItem.setText("New author...");
        fileMenu.add(newAuthorMenuItem);

        newBookMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        newBookMenuItem.setText("New book...");
        newBookMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newBookMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newBookMenuItem);

        mainMenuBar.add(fileMenu);

        setJMenuBar(mainMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fileMenuActionPerformed

    private void newBookMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newBookMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newBookMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainWindow mainWindow = new MainWindow();
                mainWindow.setVisible(true);
            }
        });
    }

    private AuthorsTableModel authorsTableModel;
    private BooksTableModel booksTableModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JPanel authorsPanel;
    private javax.swing.JScrollPane authorsScrollPane;
    private javax.swing.JTable authorsTable;
    private javax.swing.JLabel booksLabel;
    private javax.swing.JPanel booksPanel;
    private javax.swing.JScrollPane booksScrollPane;
    private javax.swing.JTable booksTable;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar mainMenuBar;
    private javax.swing.JMenuItem newAuthorMenuItem;
    private javax.swing.JMenuItem newBookMenuItem;
    // End of variables declaration//GEN-END:variables

    public class DateCellRenderer extends DefaultTableCellRenderer {

        @Override
        public Component getTableCellRendererComponent(JTable jtable, Object value, boolean selected, boolean hasFocus, int row, int column) {

            if (value instanceof Date) {

                // You could use SimpleDateFormatter instead
                value = new SimpleDateFormat("dd. MM. yyyy").format(value);

            }

            return super.getTableCellRendererComponent(jtable, value, selected, hasFocus, row, column);

        }
    }

    private void initPopupMenus() {
        JFrame t = this;

        JPopupMenu authorsPopupMenu = new JPopupMenu();
        JMenuItem deleteItem = new JMenuItem("Delete");

        authorsPopupMenu.addPopupMenuListener(new PopupMenuListener() {

            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        int rowAtPoint = authorsTable.rowAtPoint(SwingUtilities.convertPoint(authorsPopupMenu, new Point(0, 0), authorsTable));
                        if (rowAtPoint > -1) {
                            authorsTable.setRowSelectionInterval(rowAtPoint, rowAtPoint);
                            authorsTableModel.setCurrentSlectedIndex(rowAtPoint);
                        }
                    }
                });
            }

            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                // TODO Auto-generated method stub

            }

            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {
                // TODO Auto-generated method stub

            }
        });
        deleteItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    AuthorBackendWorker worker = new AuthorBackendWorker(authorsTableModel.getAuthors()
                            .get(authorsTable.getSelectedRow()), AuthorBackendWorker.Method.DELETE);
                    worker.addPropertyChangeListener(new PropertyChangeListener() {

                        @Override
                        public void propertyChange(PropertyChangeEvent evt) {
                            if (((SwingWorker.StateValue) evt.getNewValue()).equals(SwingWorker.StateValue.DONE)) {
                                updateModel();
                            }
                        }

                    });
                    worker.execute();

                } catch (IllegalStateException ex) {
                    JOptionPane.showMessageDialog(t, "Couldn't delete author. Reason: " + ex.getMessage());
                }

            }
        });
        authorsPopupMenu.add(deleteItem);
        authorsTable.setComponentPopupMenu(authorsPopupMenu);

        JPopupMenu booksPopupMenu = new JPopupMenu();
        JMenuItem deleteBook = new JMenuItem("Delete");
        booksPopupMenu.addPopupMenuListener(new PopupMenuListener() {

            @Override
            public void popupMenuWillBecomeVisible(PopupMenuEvent e) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        int rowAtPoint = booksTable.rowAtPoint(SwingUtilities.convertPoint(booksPopupMenu, new Point(0, 0), booksTable));
                        if (rowAtPoint > -1) {
                            booksTable.setRowSelectionInterval(rowAtPoint, rowAtPoint);
                        }
                    }
                });
            }

            @Override
            public void popupMenuWillBecomeInvisible(PopupMenuEvent e) {
                // TODO Auto-generated method stub

            }

            @Override
            public void popupMenuCanceled(PopupMenuEvent e) {
                // TODO Auto-generated method stub

            }
        });
        deleteBook.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                if (booksTable.getSelectedRow() == -1) {
                    JOptionPane.showMessageDialog(t, "You haven't selected any book.");
                    return;
                }
                BookBackendWorker worker = new BookBackendWorker(booksTableModel.getBooks().get(booksTable.getSelectedRow()), BookBackendWorker.Method.DELETE);
                worker.addPropertyChangeListener(new PropertyChangeListener() {

                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        if (((SwingWorker.StateValue) evt.getNewValue()).equals(SwingWorker.StateValue.DONE)) {
                            updateModel();
                        }
                    }

                });
                worker.execute();

            }
        });
        booksPopupMenu.add(deleteBook);
        booksTable.setComponentPopupMenu(booksPopupMenu);
    }

}
