/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.javaseminar.kafa.bookregister.gui;

import cz.muni.fi.javaseminar.kafa.bookregister.Author;
import cz.muni.fi.javaseminar.kafa.bookregister.AuthorManager;
import cz.muni.fi.javaseminar.kafa.bookregister.Book;
import cz.muni.fi.javaseminar.kafa.bookregister.BookManager;
import cz.muni.fi.javaseminar.kafa.bookregister.gui.backend.BackendService;
import java.awt.event.WindowEvent;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFrame;
import javax.swing.SwingWorker;
import no.tornado.databinding.model.ListComboBoxModel;
import org.jdesktop.swingx.JXDatePicker;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Martin
 */
public class NewBookWindow extends javax.swing.JFrame {

    private final AuthorManager am = BackendService.getAuthorManager();
    private final BookManager bm = BackendService.getBookManager();
    private final static Logger log = LoggerFactory.getLogger(NewBookWindow.class);

    /**
     * Creates new form NewBookWindow
     */
    public NewBookWindow() {
        initComponents();
        publishDatePanel.add(datePicker);
        new SwingWorker<Void, Void>() {
            List<String> authors;

            @Override
            protected Void doInBackground() throws Exception {
                log.debug("Fetching all authors from database for NewBookWindow.");
                authors = am.findAllAuthors()
                        .stream().map((Author x) -> x.getFirstname() + " " + x.getSurname())
                        .collect(Collectors.toList());

                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                } catch (Exception e) {
                    log.error("There was an exception thrown while inicializing NewBookWindow", e);
                    return;
                }
                log.debug("Filing ComboBox model in GUI with all authors.");
                authorComboBox.setModel(new ListComboBoxModel(authors));
                try {
                    authorComboBox.setSelectedIndex(0);
                } catch (IllegalArgumentException e) {
                    authorComboBox.setSelectedIndex(-1);
                }
            }
        }.execute();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonPanel = new javax.swing.JPanel();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        atributesPanel = new javax.swing.JPanel();
        windowLabel = new javax.swing.JLabel();
        namePanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        isbnPanel = new javax.swing.JPanel();
        isbnLabel = new javax.swing.JLabel();
        isbnTextField = new javax.swing.JTextField();
        publishDatePanel = new javax.swing.JPanel();
        publishDateLabel = new javax.swing.JLabel();
        authorPanel = new javax.swing.JPanel();
        authorLabel = new javax.swing.JLabel();
        authorComboBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(400, 250));
        setResizable(false);

        buttonPanel.setLayout(new java.awt.GridLayout(1, 2));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("cz/muni/fi/javaseminar/kafa/bookregister/gui/Bundle"); // NOI18N
        createButton.setText(bundle.getString("NewBook.create")); // NOI18N
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(createButton);

        cancelButton.setText(bundle.getString("NewBook.cancel")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(cancelButton);

        getContentPane().add(buttonPanel, java.awt.BorderLayout.SOUTH);

        atributesPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        atributesPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        atributesPanel.setLayout(new java.awt.GridLayout(6, 1));

        windowLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        windowLabel.setText(bundle.getString("NewBook.title")); // NOI18N
        atributesPanel.add(windowLabel);

        namePanel.setMaximumSize(new java.awt.Dimension(2147483647, 12));
        namePanel.setPreferredSize(new java.awt.Dimension(127, 12));
        namePanel.setLayout(new javax.swing.BoxLayout(namePanel, javax.swing.BoxLayout.LINE_AXIS));

        nameLabel.setText(bundle.getString("NewBook.name")); // NOI18N
        nameLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        nameLabel.setName(""); // NOI18N
        nameLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        namePanel.add(nameLabel);

        nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextFieldActionPerformed(evt);
            }
        });
        namePanel.add(nameTextField);

        atributesPanel.add(namePanel);

        isbnPanel.setLayout(new javax.swing.BoxLayout(isbnPanel, javax.swing.BoxLayout.LINE_AXIS));

        isbnLabel.setText(bundle.getString("NewBook.ISBN")); // NOI18N
        isbnLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        isbnLabel.setName(""); // NOI18N
        isbnLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        isbnPanel.add(isbnLabel);

        isbnTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnTextFieldActionPerformed(evt);
            }
        });
        isbnPanel.add(isbnTextField);

        atributesPanel.add(isbnPanel);

        publishDatePanel.setMaximumSize(new java.awt.Dimension(2147483647, 12));
        publishDatePanel.setPreferredSize(new java.awt.Dimension(127, 12));
        publishDatePanel.setLayout(new java.awt.GridLayout(1, 0));

        publishDateLabel.setText(bundle.getString("NewBook.publishDate")); // NOI18N
        publishDateLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        publishDateLabel.setName(""); // NOI18N
        publishDateLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        publishDateLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                publishDateLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        publishDatePanel.add(publishDateLabel);

        atributesPanel.add(publishDatePanel);

        authorPanel.setMaximumSize(new java.awt.Dimension(2147483647, 12));
        authorPanel.setPreferredSize(new java.awt.Dimension(127, 12));
        authorPanel.setLayout(new javax.swing.BoxLayout(authorPanel, javax.swing.BoxLayout.LINE_AXIS));

        authorLabel.setText(bundle.getString("NewBook.author")); // NOI18N
        authorLabel.setMinimumSize(new java.awt.Dimension(100, 16));
        authorLabel.setName(""); // NOI18N
        authorLabel.setPreferredSize(new java.awt.Dimension(80, 16));
        authorPanel.add(authorLabel);

        authorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        authorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                authorComboBoxActionPerformed(evt);
            }
        });
        authorPanel.add(authorComboBox);

        atributesPanel.add(authorPanel);

        getContentPane().add(atributesPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void isbnTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_isbnTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_isbnTextFieldActionPerformed

    private void nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextFieldActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        Instant instant;
        LocalDate date;
        JFrame t = this;
        if (datePicker.getDate() != null) {
            instant = Instant.ofEpochMilli(datePicker.getDate().getTime());
            date = LocalDateTime.ofInstant(instant, ZoneId.systemDefault()).toLocalDate();
        } else {
            date = LocalDateTime.ofInstant(Instant.now(), ZoneId.systemDefault()).toLocalDate();
        }

        Book book = new Book(null, nameTextField.getText(), isbnTextField.getText(), date, am.findAllAuthors().get(authorComboBox.getSelectedIndex()).getId());

        new SwingWorker<Void, Void>() {

            @Override
            protected Void doInBackground() throws Exception {

                log.debug("Creating new book: " + book.getName() + ". Writing it to the database.");
                bm.createBook(book);

                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                } catch (Exception e) {
                    log.error("There was an exception thrown during creation of new book.", e);
                    return;
                }

                t.dispatchEvent(new WindowEvent(t, WindowEvent.WINDOW_CLOSING));

            }

        }.execute();
    }//GEN-LAST:event_createButtonActionPerformed

    private void publishDateLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_publishDateLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_publishDateLabelAncestorAdded

    private void authorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_authorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_authorComboBoxActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_cancelButtonActionPerformed

    private JXDatePicker datePicker = new JXDatePicker();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel atributesPanel;
    private javax.swing.JComboBox authorComboBox;
    private javax.swing.JLabel authorLabel;
    private javax.swing.JPanel authorPanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JPanel isbnPanel;
    private javax.swing.JTextField isbnTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel namePanel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JLabel publishDateLabel;
    private javax.swing.JPanel publishDatePanel;
    private javax.swing.JLabel windowLabel;
    // End of variables declaration//GEN-END:variables
}
